<a href="https://colab.research.google.com/github/filkinmaksim/probability_theory_laboratory/blob/master/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B5_%D0%B7%D0%B0%D0%BD%D1%8F%D1%82%D1%82%D1%8F_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [0]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [30]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['top' 'top' 'top' 'top' 'top' 'top' 'top' 'top' '4.5' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [31]:
# Місце для Вашого коду

print(np.random.choice(10))

8


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [32]:
# Місце для Вашого коду
print(np.random.choice(10, size = (4,6)))

[[4 3 5 5 2 2]
 [5 7 6 4 0 0]
 [3 6 4 3 8 3]
 [6 0 9 4 1 4]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [33]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[4 0 3 3 3 1 4 2 4 2]


Згенеруйте одну випадкову цифру.

In [34]:
# Місце для Вашого коду

print(np.random.randint(low = 0, high = 9))

8


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [35]:
# Місце для Вашого коду

print(np.random.randint(low = 10, high=99, size = (4,5)))

[[39 87 40 28 36]
 [58 92 79 11 40]
 [46 48 73 62 65]
 [53 58 53 44 39]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [36]:
size = None
print(np.random.sample(size=size))

0.5601876633734287


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [37]:
# Місце для Вашого коду

print(np.random.sample(size = (3,4)))


[[0.17947848 0.95330001 0.7419936  0.8712505 ]
 [0.63945378 0.11641812 0.95047654 0.69939478]
 [0.56042329 0.07044948 0.15608917 0.10679917]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [0]:
a = 3
b = 5

In [39]:
# Місце для Вашого коду
print((b - a) * np.random.sample(size = 10) + a)


[3.66699033 4.089673   4.5787859  3.58576926 3.4577109  4.30262762
 3.68947184 3.48536474 4.8389379  3.78415453]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [40]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[2 4 0 5 8 1 7 6 3 9]


Перетасуйте матрицю $M$.

In [41]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [42]:
# Місце для Вашого коду

np.random.shuffle(M)
print(M)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [0]:
np.random.seed(42)

In [44]:
print(np.random.randint(10))

6


In [45]:
print(np.random.randint(10))

3


In [46]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [47]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [48]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H']


In [49]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

8 heads and 2 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [51]:
# Місце для Вашого коду
tosses=np.random.choice(["H","T"], size=100)

heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

47 heads and 53 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [54]:
# Місце для Вашого коду
tosses=np.random.randint(2, size=100)

heads = list(tosses).count(0)
tails = list(tosses).count(1)

print("{} heads and {} tails".format(heads,tails))


57 heads and 43 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [62]:
# Місце для Вашого коду
tosses=np.random.sample(size=100)
array=np.full_like(np.arange(100, dtype=float),0.5)
heads = list(tosses >= array).count(True)
tails = list(tosses >= array).count(False)

print("{} heads and {} tails".format(heads,tails))


40 heads and 60 tails


### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [64]:
# Місце для Вашого коду
n_val = [10,50,100,250,500,1000,2500,5000,10000]
for x in n_val:
    tosses=np.random.randint(2, size=x)
    heads = list(tosses).count(1)
    print("n = {} -> Possibility = {}".format(x, heads / x))


n = 10 -> Possibility = 0.5
n = 50 -> Possibility = 0.52
n = 100 -> Possibility = 0.54
n = 250 -> Possibility = 0.504
n = 500 -> Possibility = 0.516
n = 1000 -> Possibility = 0.498
n = 2500 -> Possibility = 0.49
n = 5000 -> Possibility = 0.503
n = 10000 -> Possibility = 0.5022


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [70]:
# Місце для Вашого коду
n = 60
tosses=np.random.choice([1,2,3,4,5,6], size=n)
cal = np.zeros(6, dtype=int)
for i in range(6):
    cal[i] = list(tosses).count(i + 1)
print(cal)


[10 10 12 12  8  8]


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [72]:
# Місце для Вашого коду
n_val = [10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
for x in n_val:
    tosses=np.random.choice([1,2,3,4,5,6], size=x)
    cal = np.zeros(6)
    for i in range(6):
        cal[i] = list(tosses).count(i + 1) / x
    print("n = {} -> Possibility {} ".format(x,cal))



n = 10 -> Possibility [0.3 0.3 0.  0.  0.2 0.2] 
n = 50 -> Possibility [0.22 0.18 0.22 0.08 0.12 0.18] 
n = 100 -> Possibility [0.21 0.19 0.14 0.15 0.2  0.11] 
n = 250 -> Possibility [0.128 0.168 0.148 0.236 0.164 0.156] 
n = 500 -> Possibility [0.154 0.16  0.184 0.156 0.17  0.176] 
n = 1000 -> Possibility [0.152 0.2   0.155 0.198 0.156 0.139] 
n = 2500 -> Possibility [0.1644 0.174  0.1736 0.1532 0.1692 0.1656] 
n = 5000 -> Possibility [0.1672 0.1632 0.1572 0.1722 0.1692 0.171 ] 
n = 10000 -> Possibility [0.1657 0.1651 0.1667 0.1615 0.1714 0.1696] 


## 5 Колода карт
### 5.1 Реалізація

In [73]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('5', '♡'), ('5', '♣'), ('5', '♠'), ('5', '♢'), ('9', '♡'), ('9', '♣'), ('9', '♠'), ('9', '♢'), ('6', '♡'), ('6', '♣'), ('6', '♠'), ('6', '♢'), ('J', '♡'), ('J', '♣'), ('J', '♠'), ('J', '♢'), ('K', '♡'), ('K', '♣'), ('K', '♠'), ('K', '♢'), ('1', '♡'), ('1', '♣'), ('1', '♠'), ('1', '♢'), ('4', '♡'), ('4', '♣'), ('4', '♠'), ('4', '♢'), ('3', '♡'), ('3', '♣'), ('3', '♠'), ('3', '♢'), ('10', '♡'), ('10', '♣'), ('10', '♠'), ('10', '♢'), ('7', '♡'), ('7', '♣'), ('7', '♠'), ('7', '♢'), ('8', '♡'), ('8', '♣'), ('8', '♠'), ('8', '♢'), ('2', '♡'), ('2', '♣'), ('2', '♠'), ('2', '♢'), ('Q', '♡'), ('Q', '♣'), ('Q', '♠'), ('Q', '♢')]


In [74]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

5♡, 5♣, 5♠, 5♢, 9♡, 9♣, 9♠, 9♢, 6♡, 6♣, 6♠, 6♢, J♡, J♣, J♠, J♢, K♡, K♣, K♠, K♢, 1♡, 1♣, 1♠, 1♢, 4♡, 4♣, 4♠, 4♢, 3♡, 3♣, 3♠, 3♢, 10♡, 10♣, 10♠, 10♢, 7♡, 7♣, 7♠, 7♢, 8♡, 8♣, 8♠, 8♢, 2♡, 2♣, 2♠, 2♢, Q♡, Q♣, Q♠, Q♢


In [75]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♡5, ♡9, ♡6, ♡J, ♡K, ♡1, ♡4, ♡3, ♡10, ♡7, ♡8, ♡2, ♡Q
♣5, ♣9, ♣6, ♣J, ♣K, ♣1, ♣4, ♣3, ♣10, ♣7, ♣8, ♣2, ♣Q
♠5, ♠9, ♠6, ♠J, ♠K, ♠1, ♠4, ♠3, ♠10, ♠7, ♠8, ♠2, ♠Q
♢5, ♢9, ♢6, ♢J, ♢K, ♢1, ♢4, ♢3, ♢10, ♢7, ♢8, ♢2, ♢Q


In [76]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('10', '♠'), ('6', '♢'), ('2', '♢'), ('9', '♡'), ('10', '♡'), ('1', '♢'), ('8', '♠'), ('2', '♡'), ('Q', '♣'), ('6', '♡'), ('J', '♡'), ('5', '♣'), ('8', '♣'), ('J', '♢'), ('9', '♠'), ('1', '♣'), ('1', '♡'), ('3', '♠'), ('7', '♣'), ('J', '♠'), ('9', '♢'), ('J', '♣'), ('5', '♠'), ('3', '♡'), ('10', '♣'), ('10', '♢'), ('4', '♢'), ('3', '♢'), ('7', '♢'), ('7', '♠'), ('8', '♡'), ('2', '♣'), ('K', '♢'), ('2', '♠'), ('Q', '♢'), ('Q', '♡'), ('K', '♣'), ('5', '♢'), ('6', '♠'), ('4', '♠'), ('3', '♣'), ('K', '♡'), ('1', '♠'), ('4', '♣'), ('6', '♣'), ('4', '♡'), ('5', '♡'), ('Q', '♠'), ('K', '♠'), ('9', '♣'), ('7', '♡'), ('8', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [88]:
# Місце для Вашого коду
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
Cards = [Rank + Suit for Rank in Ranks for Suit in Suits]
par = ['2','4','6','8','10']
n_val = [10,50,100,250,500,1000,2500,5000,10000]
for x in n_val:
    tosses=np.random.choice(Cards, size=x)
    cal = np.zeros(5, dtype = float)
    for i in range(5):
        for xx in Suits:
            cal[i] += list(tosses).count(par[i] + xx)
        cal[i] /= x
    print("n = {} -> Possibility {} ".format(x,cal))       
    


n = 10 -> Possibility [0.  0.2 0.  0.1 0.1] 
n = 50 -> Possibility [0.06 0.12 0.1  0.06 0.12] 
n = 100 -> Possibility [0.05 0.13 0.06 0.05 0.06] 
n = 250 -> Possibility [0.072 0.068 0.068 0.064 0.092] 
n = 500 -> Possibility [0.078 0.064 0.094 0.09  0.066] 
n = 1000 -> Possibility [0.077 0.09  0.084 0.069 0.063] 
n = 2500 -> Possibility [0.0644 0.0728 0.076  0.0724 0.0844] 
n = 5000 -> Possibility [0.0736 0.0784 0.0756 0.0754 0.0736] 
n = 10000 -> Possibility [0.0773 0.0734 0.0781 0.0769 0.0761] 


### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [0]:
# Місце для Вашого коду



### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [0]:
# Місце для Вашого коду

